# Workflow to mirror this repo to Hugging Face Spaces on every push
name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - '**'

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.GH_HF_NETFLIXSTUDIOCONNECT }}
        run: |
          git config --global credential.helper store
          echo "https://user:${HF_TOKEN}@huggingface.co" > ~/.git-credentials
          git remote add huggingface https://huggingface.co/spaces/iamkshitij/netflix-studio-connect || true
          git remote set-url huggingface https://user:${HF_TOKEN}@huggingface.co/spaces/iamkshitij/netflix-studio-connect
          git push huggingface refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* --force
